require 'rails_helper'

RSpec.describe TestViewController, :type => :controller do

  describe "GET testMap" do
    it "returns http success" do
      get :testMap
      expect(response).to have_http_status(:success)
    end
  end

  describe "GET testList" do
    it "returns http success" do
      get :testList
      expect(response).to have_http_status(:success)
    end
  end

  describe "GET testMapPhone" do
    it "returns http success" do
      get :testMapPhone
      expect(response).to have_http_status(:success)
    end
  end

  describe "GET testListPhone" do
    it "returns http success" do
      get :testListPhone
      expect(response).to have_http_status(:success)
    end
  end

##### above generated by system  #####

  describe "Map sumup info" do
    it show done events amount do
      pending
    end

    it show undone events amount do
      pending
    end
  end

  describe "Before Login" do
    describe "On message bar" do

      context "User regidter" do
        it register do
          pending
        end
      end

      context "User login" do
        it login do
          pending
        end
      end
    end

    describe "On map" do
      it shows brief events info do
        pending
      end
    end

  end

  describe "After Login" do
    describe "As a hero" do
      it able to check civilian needs do
        pending
      end
      it map help post status changed do
        pending
      end
    end

    describe "Being a civilian" do
      it civilian can post a need do
        pending
      end
    end
  end


end
